### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by boostphere** [U7P4L-IN/ENCODE#5]
![image](https://github.com/user-attachments/assets/7d01d166-af78-4588-9a85-018592b076bd)

**Comment by U7P4L-IN** [comment]
Which Terminal?

**Comment by boostphere** [comment]
in my termux and also in my ubuntu terminal

**Comment by U7P4L-IN** [comment]
Show termux issue ss😑

**Comment by boostphere** [comment]
![image](https://github.com/user-attachments/assets/7a4394a9-9a8b-4518-a3dc-c1f466f8f20a)

**Comment by U7P4L-IN** [comment]
Check this


https://www.facebook.com/U7P4L.XR/videos/775130367910145/?app=fbl

**Comment by boostphere** [comment]
but bro i want the option 16 :< the cpython best encryption

**Comment by U7P4L-IN** [comment]
bro this method also working
